include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    info: ignore
    warning: ignore

linter:
  rules:
    sort_constructors_first: false
    prefer_expression_function_bodies: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    sort_pub_dependencies: false
