name: oranzo_admin
description: "ORANZO ADMIN — master trading, finance, operations, and administration platform."
publish_to: 'none'

version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
