import 'package:flutter/material.dart';
import '../../core/backend/backend_service.dart';
import '../../core/theme/orenza_theme.dart';
import '../../core/widgets/system_states.dart';

class WalletScreen extends StatefulWidget { const WalletScreen({super.key}); @override State<WalletScreen> createState()=>_WalletScreenState(); }
class _WalletScreenState extends State<WalletScreen>{ late Future<BackendWallet> _wallet; @override void initState(){super.initState();_wallet=BackendService.instance.getWallet();} void _refresh()=>setState(()=>_wallet=BackendService.instance.getWallet());
@override Widget build(BuildContext context)=>FutureBuilder<BackendWallet>(future:_wallet,builder:(context,s){if(s.connectionState==ConnectionState.waiting)return const AurenzaLoading(message:'Loading your wallet...');if(s.hasError)return AurenzaErrorState(message:s.error.toString(),onRetry:_refresh);final w=s.data;if(w==null)return const AurenzaEmptyState(title:'Wallet unavailable',message:'The backend returned no wallet snapshot.');return RefreshIndicator(onRefresh:()async{_refresh();},child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(20),children:[_hero(w),const SizedBox(height:18),_grid(w),const SizedBox(height:20),_section('Funding & payouts',[_row('Deposit status',w.depositStatus),_row('Payout status',w.payoutStatus)]),const SizedBox(height:20),_section('Balance movements',w.movements.isEmpty?[const Padding(padding:EdgeInsets.symmetric(vertical:18),child:Text('No balance movements have been returned by the backend yet.',style:TextStyle(color:OrenzaColors.slate)))]:w.movements.map(_movement).toList())]));}
Widget _hero(BackendWallet w)=>Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(gradient:const LinearGradient(colors:[OrenzaColors.forest,OrenzaColors.forestGreen]),borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('WALLET',style:TextStyle(color:Colors.white70,fontSize:11,fontWeight:FontWeight.w800,letterSpacing:1.5)),const SizedBox(height:8),Text('${w.currency} ${w.totalBalance.toStringAsFixed(2)}',style:const TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(w.sandboxMode?'SANDBOX MODE — financial values are backend controlled':'Live account',style:const TextStyle(color:OrenzaColors.softGold,fontSize:11,fontWeight:FontWeight.w700))]));
Widget _grid(BackendWallet w){final items=[('Available balance',w.availableBalance,Icons.account_balance_outlined),('Reserved balance',w.reservedBalance,Icons.lock_outline),('Sandbox capital',w.sandboxCapital,Icons.shield_outlined),('Trading balance',w.tradingBalance,Icons.show_chart_outlined),('Profit',w.profit,Icons.trending_up),('Withdrawable',w.withdrawableBalance,Icons.payments_outlined)];return LayoutBuilder(builder:(c,x){final n=x.maxWidth>=900?3:2,g=12.0,width=(x.maxWidth-g*(n-1))/n;return Wrap(spacing:g,runSpacing:g,children:[for(final i in items)SizedBox(width:width,child:Card(child:Padding(padding:const EdgeInsets.all(15),child:Row(children:[Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:OrenzaColors.forestGreen,borderRadius:BorderRadius.circular(10)),child:Icon(i.$3,color:OrenzaColors.gold,size:19)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(i.$1,style:const TextStyle(color:OrenzaColors.slate,fontSize:11)),const SizedBox(height:4),Text('${w.currency} ${i.$2.toStringAsFixed(2)}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:14))]))]))))]);});}
Widget _section(String title,List<Widget> children)=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:10),...children])));
Widget _row(String label,String value)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[Expanded(child:Text(label,style:const TextStyle(color:OrenzaColors.slate))),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:OrenzaColors.forestGreen,borderRadius:BorderRadius.circular(20)),child:Text(value.toUpperCase(),style:const TextStyle(color:OrenzaColors.gold,fontSize:10,fontWeight:FontWeight.w800)))]));
Widget _movement(WalletMovement m)=>ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(backgroundColor:OrenzaColors.forestGreen,child:Icon(m.amount>=0?Icons.arrow_downward:Icons.arrow_upward,color:OrenzaColors.gold)),title:Text(m.description,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(m.status),trailing:Text('${m.amount>=0?'+':''}${m.amount.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.w900)));
}